name: Build Releases
on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: nightly
          default: true
          override: true
      
      - name: Install cross
        run: cargo install cross

      - name: Build ${{ matrix.target }}
        timeout-minutes: 15
        run: |
          mkdir -p ./build/release
          export RUSTFLAGS="-C link-arg=-lgcc -Clink-arg=-static-libgcc"
          cross build --target ${{ matrix.target }} -r -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
          cp ./target/${{ matrix.target }}/release/bimc ./build/release/bimc-${{ matrix.target }}
      
      - name: UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: |
            ./build/release/bimc-${{ matrix.target }}
          args: --best --lzma
      
      - name: sha256
        run: |
          cd ./build/release
          shasum -a 256 bimc-${{ matrix.target }} > bimc-${{ matrix.target }}.sha256

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/release/*
          prerelease: ${{ contains(github.ref, '-') }}
